services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/alfa_mail.db
      - SECRET_KEY=${SECRET_KEY}

  proxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Map the file from the nginx folder to the configuration
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Map certificates (must be in the main AlfaMail folder)
      - ./nginx.crt:/etc/nginx/conf.d/nginx.crt:ro
      - ./nginx.key:/etc/nginx/conf.d/nginx.key:ro
      # Map the frontend (where register.html, index.html, app.js are located)
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend

volumes:
  db_data: